import type { ThemeTokens } from "../tokens/schema";

/** Polished, high-contrast themes — one per template key. */
export const THEMES: Record<string, ThemeTokens> = {
  "gaming-club": {
    primary: "#38bdf8",
    secondary: "#0c4a6e",
    accent: "#4ade80",
    background: "#020617",
    surface: "#0f172a",
    text: "#f1f5f9",
    muted: "#94a3b8",
    border: "rgba(56, 189, 248, 0.15)",
    fontHeading: "Orbitron, system-ui, sans-serif",
    fontBody: "Inter, system-ui, sans-serif",
  },
  "esports-team": {
    primary: "#f87171",
    secondary: "#450a0a",
    accent: "#fbbf24",
    background: "#030712",
    surface: "#111827",
    text: "#fafafa",
    muted: "#a1a1aa",
    border: "rgba(248, 113, 113, 0.2)",
    fontHeading: "Rajdhani, system-ui, sans-serif",
    fontBody: "Inter, system-ui, sans-serif",
  },
  "gaming-community": {
    primary: "#a78bfa",
    secondary: "#2e1065",
    accent: "#34d399",
    background: "#0a0612",
    surface: "#1a1033",
    text: "#ede9fe",
    muted: "#a5b4fc",
    border: "rgba(167, 139, 250, 0.2)",
    fontHeading: "Space Grotesk, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
  },
  "gaming-cafe": {
    primary: "#22d3ee",
    secondary: "#083344",
    accent: "#fb923c",
    background: "#042f2e",
    surface: "#0f766e",
    text: "#ecfeff",
    muted: "#99f6e4",
    border: "rgba(34, 211, 238, 0.2)",
    fontHeading: "Exo 2, system-ui, sans-serif",
    fontBody: "Nunito, system-ui, sans-serif",
  },
  "lan-center": {
    primary: "#a3e635",
    secondary: "#14532d",
    accent: "#facc15",
    background: "#052e16",
    surface: "#166534",
    text: "#ecfccb",
    muted: "#bef264",
    border: "rgba(163, 230, 53, 0.2)",
    fontHeading: "Chakra Petch, system-ui, sans-serif",
    fontBody: "IBM Plex Sans, system-ui, sans-serif",
  },
  tournament: {
    primary: "#fbbf24",
    secondary: "#451a03",
    accent: "#ef4444",
    background: "#0c0a09",
    surface: "#1c1917",
    text: "#fafaf9",
    muted: "#d6d3d1",
    border: "rgba(251, 191, 36, 0.25)",
    fontHeading: "Bebas Neue, system-ui, sans-serif",
    fontBody: "Source Sans 3, system-ui, sans-serif",
  },
  streamer: {
    primary: "#f472b6",
    secondary: "#500724",
    accent: "#c4b5fd",
    background: "#0f0510",
    surface: "#3b0764",
    text: "#fdf2f8",
    muted: "#f9a8d4",
    border: "rgba(244, 114, 182, 0.2)",
    fontHeading: "Poppins, system-ui, sans-serif",
    fontBody: "Nunito Sans, system-ui, sans-serif",
  },
  "cyber-cafe": {
    primary: "#2dd4bf",
    secondary: "#134e4a",
    accent: "#38bdf8",
    background: "#042f2e",
    surface: "#115e59",
    text: "#f0fdfa",
    muted: "#5eead4",
    border: "rgba(45, 212, 191, 0.2)",
    fontHeading: "Titillium Web, system-ui, sans-serif",
    fontBody: "Open Sans, system-ui, sans-serif",
  },
};

export function getTheme(key: string): ThemeTokens {
  return THEMES[key] ?? THEMES["gaming-club"]!;
}
